# Generated by Django 6.1.1 on 2026-09-18 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencySimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(default='Surge scenario', max_length=255)),
                ('surge_pct', models.FloatField(default=30.0)),
                ('scope_state', models.CharField(blank=True, default='', max_length=100)),
                ('before_snapshot', models.JSONField(default=dict)),
                ('after_snapshot', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='FederatedRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('round_number', models.IntegerField()),
                ('country_updates', models.JSONField(default=list)),
                ('global_metric', models.JSONField(default=dict)),
                ('is_synthetic_demo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-round_number'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('essential', 'WHO Essential Medicine'), ('emergency', 'Emergency/Critical'), ('chronic', 'Chronic Disease'), ('maternal', 'Maternal & Child Health'), ('general', 'General')], default='general', max_length=20)),
                ('unit', models.CharField(default='units', max_length=20)),
                ('is_temperature_sensitive', models.BooleanField(default=False)),
                ('avg_lead_time_days', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('reliability_score', models.FloatField(default=0.9)),
                ('avg_lead_time_days', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_id', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('facility_type', models.CharField(choices=[('PHC', 'Primary Health Centre'), ('CHC', 'Community Health Centre'), ('SHC', 'Sub Health Centre'), ('DH', 'District Hospital')], max_length=8)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('catchment_population', models.IntegerField(default=0)),
                ('is_demo_data', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'district'], name='core_facili_state_b980b5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_beds', models.IntegerField(default=0)),
                ('occupied_beds', models.IntegerField(default=0)),
                ('doctors_sanctioned', models.IntegerField(default=0)),
                ('doctors_present', models.IntegerField(default=0)),
                ('nurses_sanctioned', models.IntegerField(default=0)),
                ('nurses_present', models.IntegerField(default=0)),
                ('specialists_sanctioned', models.IntegerField(default=0)),
                ('specialists_present', models.IntegerField(default=0)),
                ('has_cold_storage', models.BooleanField(default=False)),
                ('has_ambulance', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure', to='core.facility')),
            ],
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('horizon_days', models.IntegerField(default=14)),
                ('daily_forecast', models.JSONField(default=list)),
                ('model_used', models.CharField(default='xgboost', max_length=50)),
                ('is_demo_fallback', models.BooleanField(default=False)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='core.facility')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='core.medicine')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizedRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('stops', models.JSONField(default=list)),
                ('total_distance_km', models.FloatField(default=0)),
                ('total_eta_hours', models.FloatField(default=0)),
                ('is_demo_abstraction', models.BooleanField(default=True, help_text='True unless a real routing/traffic API is wired in — always surfaced in the UI.')),
                ('origin_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_originating', to='core.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=32, unique=True)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True, default='')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.facility')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.medicine')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='RedistributionRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_quantity', models.IntegerField()),
                ('urgency', models.CharField(default='medium', max_length=10)),
                ('reason', models.TextField(blank=True, default='')),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='recommended', max_length=20)),
                ('destination_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redistribution_destinations', to='core.facility')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redistribution_recs', to='core.medicine')),
                ('source_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redistribution_sources', to='core.facility')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_id', models.CharField(max_length=32, unique=True)),
                ('quantity', models.IntegerField()),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('eta_hours', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(default='planned', max_length=20)),
                ('urgency', models.CharField(default='medium', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_shipments', to='core.facility')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='core.medicine')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='core.order')),
                ('source_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_shipments', to='core.facility')),
            ],
        ),
        migrations.CreateModel(
            name='StockRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('current_stock', models.IntegerField()),
                ('forecasted_demand_period', models.FloatField()),
                ('incoming_supply', models.IntegerField(default=0)),
                ('projected_stock', models.FloatField()),
                ('days_of_stock', models.FloatField()),
                ('expected_stockout_date', models.DateField(blank=True, null=True)),
                ('shortage_quantity', models.FloatField(default=0)),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('explanation', models.TextField(blank=True, default='')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_risks', to='core.facility')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_risks', to='core.medicine')),
            ],
            options={
                'ordering': ['-risk_score'],
            },
        ),
        migrations.CreateModel(
            name='HMISActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opd_footfall', models.IntegerField(default=0)),
                ('ipd_admissions', models.IntegerField(default=0)),
                ('deliveries', models.IntegerField(default=0)),
                ('emergency_cases', models.IntegerField(default=0)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hmis_records', to='core.facility')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['facility', 'date'], name='core_hmisac_facilit_44d602_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opening_stock', models.IntegerField(default=0)),
                ('consumed', models.IntegerField(default=0)),
                ('received', models.IntegerField(default=0)),
                ('closing_stock', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=0)),
                ('safety_stock', models.IntegerField(default=0)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='core.facility')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='core.medicine')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['facility', 'medicine', 'date'], name='core_invent_facilit_923395_idx')],
            },
        ),
    ]
