# Generated by Django 6.1.1 on 2026-09-19 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'ordering': ['facility_id']},
        ),
    ]
